### ISSUE TITLE
Libmutter segfault on wayland

### ISSUE THREAD

**Issue by ikelos** [material-shell/material-shell#675]
**Describe the bug**
This is actually a bug in mutter (it segfaults), but material shell is the only way I know to reliably reproduce it.  Opening a gnome-terminal on the second display using the material shell app launcher, when an existing copy of gnome-terminal is already running causes a reliable segfault in libmutter.  If only one copy of terminal is running, it starts fine.  If I start it on the primary display, it starts fine.  If I start it from a shortcut key instead of through material-shell, it starts fine.

**Expected behavior**
Libmutter/wayland doesn't crash.

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [X] Wayland
- GNOME Shell version: 40.1
- Libmutter version: 40.1
- Distro: Gentoo
- Steps to reproduce, if applicable:
1. Open a copy of gnome-terminal (it doesn't matter on which display)
2. Move to the secondary display
3. Using the application launcher (does not work if launch through shortcut keys) start a second gnome-terminal window
4. Libmutter segfaults somewhere after `meta_window_move_to_monitor` (my build doesn't include debug information)

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
Jun 05 20:00:36 ikelos gnome-shell[2509010]: Timelines with detached actors are not supported
Jun 05 20:00:36 ikelos gnome-shell[2509010]: Timelines with detached actors are not supported
Jun 05 20:00:36 ikelos gnome-shell[2509010]: Timelines with detached actors are not supported
Jun 05 20:00:36 ikelos gnome-shell[2509010]: Focus MsWindow, Terminal
Jun 05 20:00:36 ikelos systemd[2504366]: Started Application launched by gnome-shell.
Jun 05 20:00:36 ikelos kernel: gnome-shell[2509010]: segfault at 18 ip 00007f842e7527af sp 00007ffcf287b220 error 4 in libmutter-8.so.0.0.0[7f842e6b7000+12f000]
Jun 05 20:00:36 ikelos kernel: Code: 3c fe ff ff 0f 1f 80 00 00 00 00 8b 8d 3c 01 00 00 85 c9 0f 85 27 fe ff ff eb 9b 41 55 41 54 55 48 89 fd 53 89 f3 48 83 ec 08 <48> 8b 47 18 4c 8b 67 30 4c 8b a8 70 02 0>
Jun 05 20:00:36 ikelos systemd[2504366]: Started VTE child process 2509993 launched by gnome-terminal-server process 2509578.
Jun 05 20:00:36 ikelos systemd[2504366]: app-gnome-org.gnome.Terminal-2509987.scope: Deactivated successfully.
Jun 05 20:00:36 ikelos systemd[1]: Started Process Core Dump (PID 2509994/UID 0).
Jun 05 20:00:37 ikelos systemd-coredump[2509995]: [🡕] Process 2509010 (gnome-shell) of user 1000 dumped core.
```

This has been happening for several months across several versions (of both material-shell and libmutter).  I didn't have enough time/patience to track down the exact situation that caused it, but my recent tests show that the gnome-terminal on the second monitor reliably causes it.  Unfortunately the coredump backtrace I've got doesn't include debugging symbols:

I triggered it reliably five times in quick succession.  Each time the backtrack looked as follows:
```
#0  0x00007fbc5a4867af in  () at /usr/lib64/libmutter-8.so.0
#1  0x00007fbc5a4e8a24 in  () at /usr/lib64/libmutter-8.so.0
#2  0x00007fbc5a4867c7 in  () at /usr/lib64/libmutter-8.so.0
#3  0x00007fbc5a4869db in  () at /usr/lib64/libmutter-8.so.0
#4  0x00007fbc5a487b8a in meta_window_move_to_monitor () at /usr/lib64/libmutter-8.so.0
#5  0x00007fbc5987bbdd in  () at /usr/lib64/libffi.so.7
#6  0x00007fbc5987b169 in  () at /usr/lib64/libffi.so.7
#7  0x00007fbc5a75995b in  () at /usr/lib64/libgjs.so.0
#8  0x00007fbc5a75a15f in  () at /usr/lib64/libgjs.so.0
#9  0x00007fbc5868b036 in  () at /usr/lib64/libmozjs-78.so.0
#10 0x00007fbc58684482 in  () at /usr/lib64/libmozjs-78.so.0
#11 0x00007fbc5867bfff in  () at /usr/lib64/libmozjs-78.so.0
#12 0x00007fbc5868ad09 in  () at /usr/lib64/libmozjs-78.so.0
#13 0x00007fbc5868b27b in  () at /usr/lib64/libmozjs-78.so.0
#14 0x00007fbc58bd4f2c in  () at /usr/lib64/libmozjs-78.so.0
#15 0x00007fbc58bd526b in  () at /usr/lib64/libmozjs-78.so.0
```

Can you offer any advice in diagnosing this?  I'm also going to file a bug with libmutter and I'll keep them in sync.

**Comment by ikelos** [comment]
Cross reference with upstream bug: https://gitlab.gnome.org/GNOME/mutter/-/issues/1832

**Comment by PapyElGringo** [comment]
I do reproduce ! Theses kind of bugs are hard to diagnosis because it's often application specific but I'll try to dig it
