### ISSUE TITLE
Build fails - metavuln-calculator semver.simplifyRange is not a function

### ISSUE THREAD

**Issue by flofeld** [material-shell/material-shell#736]
When trying to build from master it fails because of a dependency.

```
1241 verbose stack TypeError: semver.simplifyRange is not a function
1241 verbose stack     at Advisory.[calculateRange] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:191:16)
1241 verbose stack     at Advisory.load (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
1241 verbose stack     at Calculator.[calculate] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
```

**Comment by flofeld** [comment]
Downgrading as mentioned [here ](https://github.com/npm/metavuln-calculator/issues/9 )worked for now
