### ISSUE TITLE
Material Shell crashes on nixOS

### ISSUE THREAD

**Issue by IceDBorn** [material-shell/material-shell#870]
**Describe the bug**
Enabling material shell crashes gnome shell

**Expected behavior**
Material shell should not crash the gnome shell

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 42.3.1
- Distro: nixOS
- Steps to reproduce, if applicable:
1. Download material shell using the package manager or the extensions installer
2. Enable material shell
3. Crash

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
I'm not sure how to provide this on nixOS
```

**Comment by silasdavis** [comment]
> I'm not sure how to provide this on nixOS

Hm, nor am I, at leas `journalctl /run/current-system/sw/bin/gnome-shell` does not work.

I'm using version from main:
```
❯ git rev-parse --short HEAD
f4d966b
❯ gnome-shell --version
GNOME Shell 42.4
```

distro: NixOS / Wayland

Here's the relevant output from `journalctl -b  | grep gnome-shell`:

```
Aug 24 22:18:01 mifla .gnome-shell-wr[235474]: GNOME Shell started at Wed Aug 24 2022 22:17:59 GMT+0100 (BST)
Aug 24 22:18:01 mifla .gnome-shell-wr[235474]: Registering session with GDM
Aug 24 22:18:01 mifla .gnome-shell-wr[235474]: Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_iconGrid_BaseIcon>:0x50af3e0] in animation of duration 200ms but not on stage.
Aug 24 22:18:02 mifla .gnome-shell-wr[235474]: Timelines with detached actors are not supported. <unnamed>[<Gjs_ui_search_ListSearchResult>:0x4fd8f00] in animation of duration 200ms but not on stage.
Aug 24 22:18:13 mifla .gnome-shell-wr[235474]: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: WARNING: addSignalMethods is replacing existing [object Object] connect method
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: WARNING: addSignalMethods is replacing existing [object Object] emit method
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: --------------
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: INIT EXTENSION
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: --------------
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: ----------------
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: ENABLE EXTENSION
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: ----------------
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: Failed to query filesystem: method Gio.File.query_filesystem_info_async: At least 4 arguments required, but only 3 passed
Aug 24 22:18:20 mifla .gnome-shell-wr[235474]: Disabled gnome extension pop-shell@system76.com because it is incompatible with Material Shell
Aug 24 22:18:20 mifla kernel: .gnome-shell-wr[235474]: segfault at 7fffe0000000 ip 000030a7b86ab217 sp 00007fffc53cad30 error 4
Aug 24 22:18:21 mifla systemd-coredump[236566]: Process 235474 (.gnome-shell-wr) of user 1000 dumped core.
                                                Module libgnome-shell-menu.so without build-id.
                                                Module libgnome-shell.so without build-id.
                                                Module .gnome-shell-wrapped without build-id.
Aug 24 22:18:22 mifla .gnome-shell-wr[236643]: Running GNOME Shell (using mutter 42.4) as a Wayland display server
Aug 24 22:18:22 mifla .gnome-shell-wr[236643]: Device '/dev/dri/card0' prefers shadow buffer
Aug 24 22:18:22 mifla .gnome-shell-wr[236643]: Added device '/dev/dri/card0' (i915) using atomic mode setting.
Aug 24 22:18:22 mifla .gnome-shell-wr[236643]: Created gbm renderer for '/dev/dri/card0'
Aug 24 22:18:22 mifla .gnome-shell-wr[236643]: Boot VGA GPU /dev/dri/card0 selected as primary
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Using public X11 display :1024, (using :1025 for managed services)
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Using Wayland display name 'wayland-0'
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Will monitor session c10
Aug 24 22:18:23 mifla polkitd[224827]: Registered Authentication Agent for unix-session:c10 (system bus name :1.1177 [/nix/store/ak9kf50b0jskmp53qpxwmmsv9pj5hb7x-gnome-shell-42.4/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_GB.UTF-8)
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Aug 24 22:18:23 mifla .gnome-shell-wr[236643]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 24 22:18:24 mifla .gnome-shell-wr[236643]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Aug 24 22:18:24 mifla .gnome-shell-wr[236643]: ATK Bridge is disabled but a11y has already been enabled.
Aug 24 22:18:24 mifla .gnome-shell-wr[236643]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Aug 24 22:18:24 mifla .gnome-shell-wr[236643]: Registering session with GDM
Aug 24 22:18:28 mifla .gnome-shell-wr[236643]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Aug 24 22:18:28 mifla .gnome-shell-wr[236995]: Running GNOME Shell (using mutter 42.4) as a Wayland display server
Aug 24 22:18:28 mifla .gnome-shell-wr[236995]: Device '/dev/dri/card0' prefers shadow buffer
Aug 24 22:18:28 mifla .gnome-shell-wr[236995]: Added device '/dev/dri/card0' (i915) using atomic mode setting.
Aug 24 22:18:28 mifla .gnome-shell-wr[236995]: Created gbm renderer for '/dev/dri/card0'
Aug 24 22:18:28 mifla .gnome-shell-wr[236995]: Boot VGA GPU /dev/dri/card0 selected as primary
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Using public X11 display :0, (using :1 for managed services)
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Using Wayland display name 'wayland-0'
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Will monitor session 24
Aug 24 22:18:29 mifla polkitd[224827]: Registered Authentication Agent for unix-session:24 (system bus name :1.1199 [/nix/store/ak9kf50b0jskmp53qpxwmmsv9pj5hb7x-gnome-shell-42.4/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_GB.UTF-8)
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Telepathy is not available, chat integration will be disabled.
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
Aug 24 22:18:29 mifla .gnome-shell-wr[236995]: Could not issue 'GetUnit' systemd call
Aug 24 22:18:30 mifla .gnome-shell-wr[236995]: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)
Aug 24 22:18:30 mifla .gnome-shell-wr[236995]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 24 22:18:31 mifla .gnome-shell-wr[236995]: GNOME Shell started at Wed Aug 24 2022 22:18:29 GMT+0100 (BST)
Aug 24 22:18:31 mifla .gnome-shell-wr[236995]: Registering session with GDM
Aug 24 22:18:31 mifla .gnome-shell-wr[236643]: Connection to xwayland lost
Aug 24 22:18:32 mifla .gnome-shell-wr[236995]: Invalid window geometry for xdg_surface@31. Ignoring for now, but this will result in client termination in the future.
Aug 24 22:19:27 mifla .gnome-shell-wr[236995]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 24 22:19:27 mifla .gnome-shell-wr[236995]: Page flip discarded: drmModeAtomicCommit: Invalid argument
```

So looks like there is a segfault

crash occurs when enabling the extension (note I cannot re-enable extensions at all until I remove material-shell completely)

**Comment by silasdavis** [comment]
I fully removed pop-shell since the logs mention it and the same issue:

```
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: --------------
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: INIT EXTENSION
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: --------------
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: ----------------
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: ENABLE EXTENSION
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: ----------------
Aug 24 22:29:27 mifla .gnome-shell-wr[251922]: Failed to query filesystem: method Gio.File.query_filesys
tem_info_async: At least 4 arguments required, but only 3 passed
Aug 24 22:29:27 mifla kernel: .gnome-shell-wr[251922]: segfault at 7fffe0000000 ip 0000286c6cb41207 sp 0
0007ffd90d2c9f0 error 4
Aug 24 22:29:28 mifla systemd-coredump[252684]: Process 251922 (.gnome-shell-wr) of user 1000 dumped cor
e.
                                                Module libgnome-shell-menu.so without build-id.
                                                Module libgnome-shell.so without build-id.
                                                Module .gnome-shell-wrapped without build-id.
Aug 24 22:29:29 mifla .gnome-shell-wr[252755]: Running GNOME Shell (using mutter 42.4) as a Wayland disp
lay server
```

**Comment by IceDBorn** [comment]
I have exactly the same problem

**Comment by IceDBorn** [comment]
@PapyElGringo Any ideas?

**Comment by jtojnar** [comment]
Please always open an issue against your distribution if you are not sure that the project itself is responsible. Often, the issue is on distro side so it is not fair to bother upstream with it. That holds doubly for NixOS, which is very idiosyncratic.

GNOME Shell extensions commonly require [extra wrapping](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-unwrappable-package-gnome-shell-ext) on NixOS but since the packages for them are auto-generated, that might not have been done yet.

I am going to look into it later.

**Comment by jtojnar** [comment]
I rebuilt SpiderMonkey and other in a debug mode:

<details>
<summary>NixOS configuration excerpt</summary>

```nix
{ pkgs, ... }:

let
  gjs = pkgs.gjs.override {
    spidermonkey_91 = pkgs.spidermonkey_91.overrideAttrs (attrs: {
      configureFlags = attrs.configureFlags ++ [
        "--enable-debug"
      ];
      dontStrip = true;
    });
  };
in
{
  environment.systemPackages = with pkgs; [
    gdb
    binutils # readelf
    # Install debug symbols
    glib
    spidermonkey_91
    gjs
    gnome.gnome-session
    gnome.mutter
    gnome.gnome-shell
    gnomeExtensions.material-shell
  ];

  system.replaceRuntimeDependencies = [
    {
      original = pkgs.gjs;
      replacement = gjs;
    }
  ];

  environment.enableDebugInfo = true;

  nixpkgs.overlays = [
    (final: prev: {
      packagekit = prev.packagekit.overrideAttrs (attrs: {
        separateDebugInfo = true;
      });
      gnome = prev.gnome.overrideScope' (gfinal: gprev: {
        gnome-session = gprev.gnome-session.overrideAttrs (attrs: {
          separateDebugInfo = true;
        });
        gnome-shell = gprev.gnome-shell.overrideAttrs (attrs: {
          separateDebugInfo = true;
        });
        mutter = gprev.mutter.overrideAttrs (attrs: {
          separateDebugInfo = true;
        });
      });
    })
  ];
}
```

</details>

And it does not look like the fault is with either NixOS or the extension (at least I would not expect extension to be able to crash the JS runtime like this):

```gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  JS::Value::setDouble (d=<optimized out>, this=<optimized out>) at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/Value.h:471
471	    MOZ_ASSERT(isDouble());
[Current thread is 1 (Thread 0x7f444ab1ddc0 (LWP 1401))]
(gdb) bt
#0  JS::Value::setDouble (d=<optimized out>, this=<optimized out>) at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/Value.h:471
#1  0x00007f44513c73e8 in JS::Value::setDouble (d=<optimized out>, this=<synthetic pointer>) at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/mozilla/Vector.h:487
#2  JS::Value::setNumber (f=<optimized out>, this=<synthetic pointer>) at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/Value.h:530
#3  JS::NumberValue<float> (t=<optimized out>) at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/Value.h:1031
#4  js::MutableWrappedPtrOperations<JS::Value, JS::MutableHandle<JS::Value> >::setNumber<float> (t=<optimized out>, this=0x7ffcc7f3f7e0)
    at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/Value.h:1204
#5  gjs_value_from_g_argument (context=<optimized out>, value_p=..., type_info=0x2756858, arg=0x54dd480, copy_structs=<optimized out>) at ../gi/arg.cpp:2480
#6  0x00007f4451417fca in Gjs::Function::invoke (this=0x2766730, context=<optimized out>, args=..., this_obj=..., r_value=<optimized out>)
    at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/RootingAPI.h:1192
#7  0x00007f44514188b2 in Gjs::Function::call (context=context@entry=0x137e920, js_argc=<optimized out>, vp=<optimized out>) at ../gi/function.cpp:1148
#8  0x00007f444ec412c7 in CallJSNative (cx=0x137e920, native=0x7f44514186f0 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, reason=reason@entry=js::CallReason::Call, args=...)
    at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:426
#9  0x00007f444ec5f7c6 in js::InternalCallOrConstruct (cx=<optimized out>, args=..., construct=js::NO_CONSTRUCT, reason=js::CallReason::Call) at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:497
#10 0x00007f444ec53043 in js::CallFromStack (args=..., cx=<optimized out>) at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:575
#11 Interpret (cx=0x137e920, state=...) at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:3226
#12 0x00007f444ec5eeb6 in js::RunScript (cx=0x137e920, state=...) at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:395
#13 0x00007f444ec5f4b6 in js::InternalCallOrConstruct (cx=<optimized out>, args=..., construct=js::NO_CONSTRUCT, reason=<optimized out>) at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:543
#14 0x00007f444ec5f9b8 in js::Call (cx=<optimized out>, fval=..., fval@entry=..., thisv=..., thisv@entry=..., args=..., rval=rval@entry=..., reason=reason@entry=js::CallReason::Call)
    at /build/firefox-91.12.0/js/src/vm/Interpreter.cpp:588
#15 0x00007f444ed1cf88 in JS_CallFunctionValue (cx=<optimized out>, obj=..., fval=..., args=..., rval=...) at /build/firefox-91.12.0/js/src/jsapi.cpp:2722
#16 0x00007f4451453343 in GjsContextPrivate::call_function (this=this@entry=0x1370070, this_obj=..., this_obj@entry=..., func_val=..., func_val@entry=..., args=..., rval=...) at ../gjs/context.cpp:1605
#17 0x00007f4451428ca6 in ObjectInstance::constructor_impl (this=<optimized out>, context=<optimized out>, object=..., argv=...)
    at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/RootingAPI.h:1193
#18 0x00007f4451434ca4 in GIWrapperBase<ObjectBase, ObjectPrototype, ObjectInstance>::constructor (cx=<optimized out>, argc=<optimized out>, vp=<optimized out>)
    at /nix/store/sdx44ds1jfdcswjp6a21hm9jwvylgnsy-spidermonkey-91.12.0-dev/include/mozjs-91/js/RootingAPI.h:1193
#19 0x00002c50323d96ed in ?? ()
#20 0x000000000137e920 in ?? ()
#21 0x00007ffcc7f408a8 in ?? ()
#22 0xfffe1ceb15178718 in ?? ()
#23 0x0000000000000001 in ?? ()
#24 0xfffe1ceb15178718 in ?? ()
#25 0x0000000000003822 in ?? ()
#26 0x0000000000000001 in ?? ()
#27 0xfff9800000000000 in ?? ()
#28 0xfffa800000000005 in ?? ()
#29 0xfffe1ceb15178698 in ?? ()
#30 0xfffe121af3944f28 in ?? ()
#31 0x00007ffcc7f40978 in ?? ()
#32 0x00000000054fbfc0 in ?? ()
#33 0x00002c50322f7332 in ?? ()
#34 0x0000000000007821 in ?? ()
#35 0xfffe121af3944f28 in ?? ()
#36 0xfffe1ceb15178718 in ?? ()
#37 0xfffa800000000005 in ?? ()
#38 0xfffe0bf7e35e5e40 in ?? ()
#39 0xfffa80000000000a in ?? ()
#40 0x00000f59f7c3c240 in ?? ()
#41 0x0000000002099533 in ?? ()
#42 0x00000000055342f8 in ?? ()
#43 0x00000bf7e358c830 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#44 0x00000000055342d0 in ?? ()
#45 0x00007ffcc7f409c8 in ?? ()
#46 0x00007ffcc7f40b60 in ?? ()
#47 0x0000007800000002 in ?? ()
#48 0x00007ffcc7f409b0 in ?? ()
#49 0x00007ffcc7f409f0 in ?? ()
#50 0x00002c50322c0e34 in ?? ()
#51 0x0000000000002043 in ?? ()
#52 0x00000f59f7c9be09 in ?? ()
#53 0x0000000000000001 in ?? ()
#54 0xfffa80000000000a in ?? ()
#55 0xfffe1ceb15178718 in ?? ()
#56 0xfffe121af3944f28 in ?? ()
#57 0x000000000137e920 in ?? ()
#58 0x00007ffcc7f40aa0 in ?? ()
#59 0x00007ffcc7f40a90 in ?? ()
#60 0x00007ffcc7f40a70 in ?? ()
#61 0x000000000137e920 in ?? ()
#62 0x00007ffcc7f40ab0 in ?? ()
#63 0x00007ffcc7f40e50 in ?? ()
#64 0x00007ffcc7f40d80 in ?? ()
#65 0x00007f444f60a5b9 in EnterJit (cx=<optimized out>, state=..., code=0x7ffcc7f40740 "8\351\067\001") at /build/firefox-91.12.0/obj/dist/include/js/RootingAPI.h:1192
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

It looks like we have spidermonkey 91.12.0esr so I can try updating it to latest 91.13.0esr, otherwise we will just need to wait if gjs [update from GNOME 43](https://github.com/NixOS/nixpkgs/pull/182618), which will hopefully land this/next week.

**Comment by dunk1452** [comment]
I can confirm this issue has been fixed with gnome 43 on the nixos-unstable channel.
